---
- name: test if autofs_maps is set correctly
  assert:
    that:
      - autofs_maps | length > 0
      - autofs_maps is iterable
    quiet: yes
  when:
    - autofs_maps is defined

- name: test if item in autofs_maps is set correctly
  assert:
    that:
      - item.mountpoint is defined
      - item.mountpoint | length > 0
      - item.directories is defined
      - item.directories | length > 0
      - item.directories is iterable
    quiet: yes
  loop: "{{ autofs_maps }}"
  loop_control:
    label: "{{ item.mountpoint }}"

- name: test if options item in autofs_maps is set correctly
  assert:
    that:
      - item.options | length > 0
      - item.options is iterable
    quiet: yes
  loop: "{{ autofs_maps }}"
  loop_control:
    label: "{{ item.mountpoint }}"
  when:
    - item.options is defined
