---
# handlers file for autofs

- name: restart autofs
  service:
    name: "{{ autofs_service }}"
    state: restarted

- name: reload autofs
  service:
    name: "{{ autofs_service }}"
    state: reloaded
