---
# handlers file for autofs

- name: restart autofs
  service:
    name: "{{ autofs_service }}"
    state: restarted
  when:
    - not ansible_check_mode | bool

- name: reload autofs
  service:
    name: "{{ autofs_service }}"
    state: reloaded
  when:
    - not ansible_check_mode | bool
