---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-autofs
      autofs_maps:
        - mountpoint: /bind
          directories:
            - path: mount
              server: ":/mnt"
              options:
                - "fstype=bind"
        - mountpoint: /do_not_exist
          state: absent
      nis_master_map: auto.master

  tasks:
    - name: check /bind
      stat:
        path: /bind
      register: autofs_test_bind
      failed_when:
        - not autofs_test_bind.stat.exists
