---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: ansible-role-autofs
      autofs_maps:
        - mountpoint: /bind
          directories:
            - path: mount
              server: ":/mnt"
              options:
                - "fstype=bind"
        - mountpoint: /do_not_exist
          state: absent

  tasks:
    - name: test /bind
      stat:
        path: /bind
      register: autofs_test_bind

    - name: check if /bind exists
      assert:
        that:
          - autofs_test_bind.stat.exists
        quiet: yes
