---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-autofs
      autofs_maps:
        - mountpoint: /bind
          options:
            - "fstype=bind"
          directories:
            - path: mount
              server: ":/mnt"

  tasks:
    - name: write test in automounted /bin/mount
      file:
        path: /bind/mount/test
        state: touch
        mode: "0644"

    - name: record status of /bind/mount/test
      stat:
        path: /mnt/test
      register: autofs_check_test_source

    - name: check if /bind/mount/test exists
      assert:
        that:
          - autofs_check_test_source.stat.exists
      quiet: yes
