---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: check that the path is available at the mountpoint
      stat:
        path: /bind/mnt/mount
      register: autofs_test_bind
      failed_when:
        - not autofs_test_bind.stat.exists
