---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - vars.yml

  tasks:
    - name: check that the path is available at the mountpoint
      stat:
        path: "{{ mountpoint }}/{{ path }}"
      register: autofs_test_bind
      failed_when:
        - not autofs_test_bind.stat.exists
